### ISSUE TITLE
Crash when importing transactions

### ISSUE THREAD

**Issue by neustifter** [stereolith/fints-to-ynab#1]
When I want to import transactions from the comdirect bank I get the following stacktrace.

I try to set it up on my synology DSM with pyhton 3.8.1.

Traceback (most recent call last):
  File "fints_to_ynab.py", line 56, in <module>
    transactions = fints_importer.get_transactions(bank_config)
  File "/volume1/homes/chefkoch/FinTS YNAB Importer/fints_importer.py", line 46, in get_transactions
    return list(map(lambda t: transform_fints_transaction(t.data, parse_paypal=bank_config.parse_paypal), transactions))
  File "/volume1/homes/chefkoch/FinTS YNAB Importer/fints_importer.py", line 46, in <lambda>
    return list(map(lambda t: transform_fints_transaction(t.data, parse_paypal=bank_config.parse_paypal), transactions))
  File "/volume1/homes/chefkoch/FinTS YNAB Importer/fints_importer.py", line 19, in transform_fints_transaction
    cash_withdrawl= True if "BARGELD" in transaction['posting_text'] else False
TypeError: argument of type 'NoneType' is not iterable

**Comment by stereolith** [comment]
Could reproduce this with my own Comdirect account. The issue was that the 'posting_text'-field in the finTS transaction is emtpy in the Comdirect transactions (could only test with one transaction though). This could mean that the cash withdrawl detection function could not work for you.

Added handling of that empty field in https://github.com/stereolith/fints-to-ynab/commit/3c5af8b606454e184f5f81fb25a9a5a100ea4f7a , on current master. Please test.

**Comment by neustifter** [comment]
Tested with 3c5af8b and it worked.
