### ISSUE TITLE
Cannot run this with cron - settings.json not found

### ISSUE THREAD

**Issue by Astronautikus** [stereolith/fints-to-ynab#4]
When I try to run that via cronjob it gives me an error "settings.json not found"
Also when I try to run the script via "python3 /path/to/script/fints_to_ynab.py" I'm getting this error.

print(config_file_path) gives me just "settings.json" - so the file path seems to be missing.

Any idea how to fix this?

Besides that your script is working like a charm! Thank you!

**Comment by Astronautikus** [comment]
This worked for me - not sure if that is a good solution as I'm not familiar with python.
```
    def __init__(self, config_file_path: str):
        # init config pbjects with path to config file
        config_file_path = os.path.dirname(__file__) + '/' + config_file_path
        try:
            with open(config_file_path) as f:
```

**Comment by stereolith** [comment]
The script only works when it is execued from the same directory it is saved in, especially because the other script library files are imported relatively. In my crontab I used `cd` to solve this.

My crontab entry:
`0 */3 * * * cd /home/lukas/fints-to-ynab/ && venv/bin/python3.8 fints_to_ynab.py >> import.log`

I also added the example crontab entry to the readme.
